// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate/introspect necesitan la conexión directa (sin pooler) para DDL;
    // la app en runtime usa DATABASE_URL (pooled) vía el adapter en
    // src/lib/db/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
